---
name: Top-level CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main  # Comment this line if you want to test the CI before opening a PR

jobs:
  global:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version-file: .python-version
          cache: 'pip'
          cache-dependency-path: |
            pip-requirements.txt
            dev-requirements.txt

      - name: Install Python dependencies
        run: |
          pip install -r pip-requirements.txt
          pip install -r dev-requirements.txt

      - name: Format Python imports
        run: |
          isort --check-only .

      - name: Format Python
        run: |
          black --check .

      - name: Lint Python
        run: |
          flake8 .

      - name: Lint Python doc
        run: |
          pylint .
